language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
script: 
  - npm run test
  - npm run coverage
cache:
  directories:
    - "node_modules"
after_success:
  - npm install -g coveralls
  - coveralls < ./coverage/lcov.info